src/customers/urls.py
from django.urls import path

from customers.views import CustomerCreateView, add_form, CustomerUpdateView, CustomerListView, CustomerDeleteView, \
    CustomerDetailView

app_name = "customers"

urlpatterns = [
    path("create/", CustomerCreateView.as_view(), name="customer_create"),
    path("<int:pk>/", CustomerDetailView.as_view(), name="customer_detail"),
    path("<int:pk>/update/", CustomerUpdateView.as_view(), name="customer_update"),
    path("<int:pk>/delete/", CustomerDeleteView.as_view(), name="customer_delete"),
    path("", CustomerListView.as_view(), name="customer_list"),
    path("partials/add_form/", add_form, name="add_form"),
]

src/runnersutah/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("customers/", include("customers.urls")),
]

src/customers/models.py
from django.contrib.auth import get_user_model
from django.db import models

from products.models import Product

User = get_user_model()


class Customer(models.Model):
    """
    Represents a customer with an associated user account.

    Reverse lookups:
     - notification_groups: NotificationGroup instances with this user
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    display_name = models.CharField(blank=False, null=False, max_length=255)
    phone_number = models.CharField(blank=True, max_length=255)
    status = models.CharField(blank=False, default="Active", max_length=255)
    products = models.ManyToManyField("products.Product", blank=True)

    def __str__(self) -> str:
        return f"{self.user} ({self.phone_number}) {self.status}"


class NotificationGroup(models.Model):
    """
    Represents a collection of email addresses with shared notification preferences, assigned to a customer.

    Reverse lookups:
     - emails: Email addresses associated with this group.
    """

    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="notification_groups"
    )
    name = models.CharField(blank=False, null=False, max_length=255)
    templates = models.ManyToManyField(
        "products.ProductTemplate",
        blank=True,
        related_name="notification_groups",
        help_text="Product templates this group wants to be notified for.",
    )

    def __str__(self) -> str:
        return f"{self.name} ({self.customer.display_name})"


class Email(models.Model):
    """
    Represents an email address that must be unique within a notification group.
    """

    group = models.ForeignKey(
        NotificationGroup, on_delete=models.CASCADE, related_name="emails"
    )
    address = models.EmailField()

    class Meta:
        # Enforce only one instance of an email address in a group
        constraints = [
            models.UniqueConstraint(
                fields=["group", "address"], name="unique_email_address"
            )
        ]

    def __str__(self) -> str:
        return self.address

src/customers/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms.models import (
    inlineformset_factory,
    BaseInlineFormSet,
)
from django.utils.translation import gettext_lazy as _

from customers.models import Customer, NotificationGroup, Email
from products.models import Product


def is_empty_form(form):
    return form.is_valid() and not form.cleaned_data


def is_form_persisted(form):
    return bool(getattr(form.instance, "pk", None))


def is_adding_nested_inlines_to_empty_form(form):
    if (
        not hasattr(form, "nested")
        or is_form_persisted(form)
        or not is_empty_form(form)
    ):
        return False

    for formset in form.nested:
        non_deleted_forms = set(formset.forms).difference(set(formset.deleted_forms))
        for nested_form in non_deleted_forms:
            if not is_empty_form(nested_form):
                return True

    return False


class EmailFormSetBase(BaseInlineFormSet):
    pass


EmailFormSet = inlineformset_factory(
    NotificationGroup,
    Email,
    formset=EmailFormSetBase,
    fields=("address",),
    extra=0,
)


class NotificationGroupWithEmailsFormSet(BaseInlineFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)

        email_formset = EmailFormSet(
            instance=form.instance,
            data=form.data if form.is_bound else None,
            files=form.files if form.is_bound else None,
            prefix=f"{form.prefix}-{EmailFormSet.get_default_prefix()}",
        )
        form.nested = (email_formset,)

    def is_valid(self):
        result = super().is_valid()
        if self.is_bound:
            for form in self.forms:
                if hasattr(form, "nested"):
                    result = result and all(f.is_valid() for f in form.nested)
        return result

    def clean(self):
        super().clean()
        for form in self.forms:
            if not hasattr(form, "nested") or form.cleaned_data.get("DELETE"):
                continue
            if is_adding_nested_inlines_to_empty_form(form):
                form.add_error(
                    field=None,
                    error=_(
                        "You are trying to add emails to a group which does not exist, please add information about"
                        "the group and add the emails again."
                    ),
                )

    def save(self, commit=True):
        result = []

        for form in self.forms:
            if form.cleaned_data.get("DELETE"):
                if form.instance.pk and commit:
                    form.instance.delete()
                continue

            instance = form.save(commit=commit)
            result.append(instance)

            if hasattr(form, "nested") and not is_adding_nested_inlines_to_empty_form(
                form
            ):
                for formset in form.nested:
                    formset.save(commit=commit)

        return result


NotificationGroupFormSet = inlineformset_factory(
    Customer,
    NotificationGroup,
    formset=NotificationGroupWithEmailsFormSet,
    fields=("name",),
    extra=0,
)


class CreateCustomerForm(UserCreationForm):
    display_name = forms.CharField(max_length=250)
    phone_number = forms.CharField(max_length=250, required=False)
    products = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = get_user_model()
        fields = [
            "display_name",
            "phone_number",
            "products",
            "email",
            "username",
            "password1",
            "password2",
        ]

    def save(self, commit=True):
        user = super().save(commit=commit)

        customer = Customer.objects.create(
            user=user,
            display_name=self.cleaned_data.get("display_name"),
            phone_number=self.cleaned_data.get("phone_number", ""),
        )
        customer.products.set(self.cleaned_data.get("products", []))

        return customer


class UpdateCustomerForm(forms.ModelForm):
    display_name = forms.CharField(max_length=250)
    phone_number = forms.CharField(max_length=250, required=False)
    products = forms.ModelMultipleChoiceField(
        queryset=Product.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    email = forms.EmailField(max_length=250, required=False)

    class Meta:
        model = Customer
        fields = [
            "display_name",
            "phone_number",
            "products",
            "email",
        ]

    def save(self, commit=True):
        customer = super().save(commit=False)

        user = customer.user
        user.email = self.cleaned_data.get("email")
        user.save()

        customer.display_name = self.cleaned_data.get("display_name")
        customer.phone_number = self.cleaned_data.get("phone_number", "")
        if commit:
            customer.save()
            customer.products.set(self.cleaned_data.get("products", []))
        return customer

src/customers/views.py
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST
from django.urls.base import reverse_lazy
from django.views.generic import ListView, DeleteView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.utils.module_loading import import_string
from django.template.loader import render_to_string
from django.http import HttpResponse

from customers.forms import (
    CreateCustomerForm,
    NotificationGroupFormSet,
    UpdateCustomerForm,
)
from customers.models import Customer


User = get_user_model()


def assign_class(formset):
    formset.formset_class = (
        f"{formset.__class__.__bases__[0].__module__}.{formset.__class__.__name__}"
    )

    for form in formset.forms:
        if hasattr(form, "nested"):
            for nested in form.nested:
                assign_class(nested)

    if hasattr(formset.empty_form, "nested"):
        for nested in formset.empty_form.nested:
            assign_class(nested)


class CustomerCreateView(CreateView):
    model = Customer
    template_name = "customers/customer_create.html"
    form_class = CreateCustomerForm
    success_url = reverse_lazy("customers:customer_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        notification_group_formset = NotificationGroupFormSet(
            self.request.POST or None,
            prefix="notification_group_formset",
        )
        assign_class(notification_group_formset)

        context["formsets"] = (notification_group_formset,)
        return context

    def form_valid(self, form):
        response = super().form_valid(form)

        notification_group_formset = NotificationGroupFormSet(
            self.request.POST,
            instance=self.object,
            prefix="notification_group_formset",
        )

        if notification_group_formset.is_valid():
            notification_group_formset.save()

        return response


class CustomerDetailView(DetailView):
    model = Customer
    template_name = "customers/customer_detail.html"


class CustomerUpdateView(UpdateView):
    model = Customer
    template_name = "customers/customer_update.html"
    form_class = UpdateCustomerForm
    success_url = reverse_lazy("customers:customer_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        notification_group_formset = NotificationGroupFormSet(
            self.request.POST or None,
            instance=self.object,
            prefix="notification_group_formset",
        )
        assign_class(notification_group_formset)

        context["formsets"] = (notification_group_formset,)
        return context

    def form_valid(self, form):
        response = super().form_valid(form)

        notification_group_formset = NotificationGroupFormSet(
            self.request.POST,
            instance=self.object,
            prefix="notification_group_formset",
        )

        if notification_group_formset.is_valid():
            notification_group_formset.save()

        return response

    def get_initial(self):
        initial = super().get_initial()

        initial["email"] = self.object.user.email

        return initial


class CustomerDeleteView(DeleteView):
    model = Customer
    template_name = "customers/customer_confirm_delete.html"
    success_url = reverse_lazy("customers:customer_list")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        user = self.object.user

        response = super().delete(request, *args, **kwargs)

        if user:
            user.delete()

        return response


class CustomerListView(ListView):
    model = Customer
    template_name = "customers/customer_list.html"


@require_POST
def add_form(request):
    class_path = request.POST.get("formset_class")
    prefix = request.POST.get("formset_prefix")
    total_forms = int(request.POST.get(f"{prefix}-TOTAL_FORMS", 0))

    FormSetClass = import_string(class_path)
    formset = FormSetClass(prefix=prefix)
    empty_form = formset.empty_form

    if hasattr(empty_form, "nested"):
        for nested_fs in empty_form.nested:
            assign_class(nested_fs)

    form_html = render_to_string(
        "base/partials/form.html", {"form": empty_form}, request=request
    )
    form_html = form_html.replace("__prefix__", str(total_forms))

    return HttpResponse(form_html)

templates/customers/customer_confirm_delete.html
<h1>Delete Customer</h1>

<p>
    Are you sure you want to delete
    <strong>{{ object }}</strong>
    and the associated user account?
</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">
        Yes, delete
    </button>
    <a href="{% url 'customers:customer_list' %}">
        Cancel
    </a>
</form>

templates/customers/customer_create.html
{% extends "base/base.html" %}

{% block head %}
<title>Create Customer</title>
{% endblock %}

{% block body %}
<div class="card">
    <h1 class="card-title">Create Customer</h1>
    <p class="card-description">Enter your customer information.</p>
    <hr>
    <form method="post">
        {% csrf_token %}

        <div class="customer-form">
            <h2 class="form-label">Full Name:</h2>
            {{ form.display_name }}
            {% if "display_name" in form.errors %}
            <b class="error-message">{{ form.errors.display_name }}</b>
            {% endif %}

            <h2 class="form-label">Email Address:</h2>
            {{ form.email }}
            {% if "email" in form.errors %}
            <b class="error-message">{{ form.errors.email }}</b>
            {% endif %}

            <h2 class="form-label">Phone Number:</h2>
            {{ form.phone_number }}
            {% if "phone_number" in form.errors %}
            <b class="error-message">{{ form.errors.phone_number }}</b>
            {% endif %}

            <h2 class="form-label">Username:</h2>
            {{ form.username }}
            {% if "username" in form.errors %}
            <b class="error-message">{{ form.errors.username }}</b>
            {% endif %}

            <h2 class="form-label">Password:</h2>
            {{ form.password1 }}
            {% if "password1" in form.errors %}
            <b class="error-message">{{ form.errors.password1 }}</b>
            {% endif %}

            <h2 class="form-label">Retype Password:</h2>
            {{ form.password2 }}
            {% if "password2" in form.errors %}
            <b class="error-message">{{ form.errors.password2 }}</b>
            {% endif %}
        </div>

        <h2 class="form-label">Notification Groups</h2>
        {% include "base/partials/nested_formset.html" with formsets=formsets %}

        <br>
        <input type="submit" value="Save Changes">
    </form>
</div>
{% endblock %}

templates/customers/customer_detail.html
{% extends "base/base.html" %}

{% block head %}
    <title>{{ customer.display_name }} Info</title>
{% endblock %}

{% block body %}
    <dl>
        <dt>ID</dt>
        <dd>{{ customer.id }}</dd>

        <dt>User</dt>
        <dd>{{ customer.user }}</dd>

        <dt>Name</dt>
        <dd>{{ customer.display_name }}</dd>

        <dt>Phone</dt>
        <dd>{{ customer.phone_number }}</dd>

        <dt>Status</dt>
        <dd>{{ customer.status }}</dd>

        <dt>Products</dt>
        <dd>{{ customer.products }}</dd>
    </dl>

    <a href="{% url 'customers:customer_update' customer.pk %}">Update</a>
    <a href="{% url 'customers:customer_delete' customer.pk %}">Delete</a>
    <a href="{% url 'customers:customer_list' %}">Back</a>
{% endblock %}

templates/customers/customer_list.html
{% extends "base/base.html" %}

{% block head %}
    <title>Customers</title>
{% endblock %}

{% block body %}
    {% for object in object_list %}
        <a href="{% url 'customers:customer_update' object.pk %}">{{ object.display_name }}</a>
        {{ object }}
        <a href="{% url 'customers:customer_detail' object.pk %}">Detail</a>
        <a href="{% url 'customers:customer_delete' object.pk %}">Delete</a>
        <br>
    {% endfor %}
    <a href="{% url 'customers:customer_create' %}">Create Customer</a>
{% endblock %}

templates/customers/customer_update.html
{% extends "base/base.html" %}

{% block head %}
    <title>Update {{ form.display_name }}</title>
{% endblock %}

{% block body %}
<div class="card">
    <h1 class="card-title">Edit Customer</h1>
    <p class="card-description">Enter your customer information.</p>
    <hr>
    <form method="post">
        {% csrf_token %}

        <div class="customer-form">
            <h2 class="form-label">Full Name:</h2>
            {{ form.display_name }}
            {% if "display_name" in form.errors %}
            <b class="error-message">{{ form.errors.display_name }}</b>
            {% endif %}

            <h2 class="form-label">Email Address:</h2>
            {{ form.email }}
            {% if "email" in form.errors %}
            <b class="error-message">{{ form.errors.email }}</b>
            {% endif %}

            <h2 class="form-label">Phone Number:</h2>
            {{ form.phone_number }}
            {% if "phone_number" in form.errors %}
            <b class="error-message">{{ form.errors.phone_number }}</b>
            {% endif %}
        </div>

        <h2 class="form-label">Notification Groups</h2>
        {% include "base/partials/nested_formset.html" with formsets=formsets %}

        <br>
        <input type="submit" value="Save Changes">
    </form>
</div>
{% endblock %}