src/customers/urls.py
from django.urls import path

from customers.views import CustomerCreateView, add_form, CustomerUpdateView, CustomerListView, CustomerDeleteView, \
    CustomerDetailView

app_name = "customers"

urlpatterns = [
    path("create/", CustomerCreateView.as_view(), name="customer_create"),
    path("<int:pk>/", CustomerDetailView.as_view(), name="customer_detail"),
    path("<int:pk>/update/", CustomerUpdateView.as_view(), name="customer_update"),
    path("<int:pk>/delete/", CustomerDeleteView.as_view(), name="customer_delete"),
    path("", CustomerListView.as_view(), name="customer_list"),
    path("partials/add_form/", add_form, name="add_form"),
]

src/runnersutah/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("customers/", include("customers.urls")),
]

templates/base/partials/form.html
<div class="form">
    {{ form }}

    {% if form.nested %}
        {% include "base/partials/nested_formset.html" with formsets=form.nested %}
    {% endif %}
</div>

templates/base/partials/nested_formset.html
<div class="formsets">
    {% for formset in formsets %}
        <div class="formset">
            <div class="management-form">
                {{ formset.management_form }}
            </div>
            <div class="forms" id="{{ formset.prefix }}-forms">
                {% for form in formset %}
                    {{ form.errors }}
                    {% include "base/partials/form.html" with form=form %}
                {% endfor %}
            </div>
            <button
                    hx-post="{% url 'customers:add_form' %}"
                    hx-target="#{{ formset.prefix }}-forms"
                    hx-swap="beforeend"
                    hx-vals='{
                        "formset_class": "{{ formset.formset_class }}",
                        "formset_prefix": "{{ formset.prefix }}"
                    }'
                    type="button">
                    Add Form
            </button>
        </div>
    {% endfor %}
</div>